
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web.MVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SanPham
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SanPham()
    {

        this.ChiTietHoaDon = new HashSet<ChiTietHoaDon>();

        this.GioHang = new HashSet<GioHang>();

    }


    public int Id { get; set; }

    public string TenSP { get; set; }

    public string Anh { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public Nullable<double> DonGiaBan { get; set; }

    public Nullable<double> DonGiaNhap { get; set; }

    public Nullable<System.DateTime> NgayNhap { get; set; }

    public Nullable<int> NhaSanXuatId { get; set; }

    public string MoTa { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietHoaDon> ChiTietHoaDon { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GioHang> GioHang { get; set; }

    public virtual NhaSanXuat NhaSanXuat { get; set; }

}

}
